version: "3.8"
services:
  app:
    build: .
    container_name: email_signature_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - BULK_QUEUE_NAME=${BULK_QUEUE_NAME}
      - PORT=${PORT}
      - POSTGRES_HOST=email_signature_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=email_signatures
    depends_on:
      email_signature_db:
        condition: service_healthy
      email_signature_redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/templates:/app/templates

  email_signature_redis:
    image: redis:latest
    container_name: email_signature_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  email_signature_db:
    image: postgres:15
    container_name: email_signature_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: email_signatures
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d email_signatures" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
